name: Feature Request
description: Suggest an idea for the SILC Protocol
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - boss
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature for SILC Protocol!
  
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
  
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  
  - type: dropdown
    id: component
    attributes:
      label: Which component would this feature affect?
      multiple: true
      options:
        - Signal Processing
        - Core Protocol
        - Message Format
        - Memory Management
        - Dialect System
        - Transport Layer
        - Security
        - Protocol Bridges
        - New Component
  
  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      options:
        - Critical - Blocking my use case
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Future consideration
    validations:
      required: true
  
  - type: textarea
    id: implementation
    attributes:
      label: Implementation ideas
      description: If you have ideas on how this could be implemented, please share them.
      placeholder: |
        - Modify the signal encoder to...
        - Add a new method to SILCProtocol that...
        - Create a new dialect pattern for...
  
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, mockups, or examples about the feature request here.
  
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to contribute to implementing this feature
          required: false